### ISSUE TITLE
profile command doesn't return anything

### ISSUE THREAD

**Issue by ghost** [aperpen/clash-royale-client#10] opened 2018-08-15 15:35 UTC
When I type in 'profile #...' (I did press Alt + C before) it only returns

KeepAlive
KeepAliveOk
FetchProfile
26833

same goes for the clan command
every other command is fine

**Comment by aperpen** [comment] 2018-08-16 14:35
It seems like the tag doesn't exists.
What tags are you using? Remember that tags always use 0 (_zero_) and never O.

**Comment by ghost** [comment] 2018-08-18 13:18
I tried a couple different ones, but e.g. 9PJ8U8RY doesn't work (with or without the #).

**Comment by aperpen** [comment] 2018-08-20 22:56
![image](https://user-images.githubusercontent.com/24506783/44370975-ec5bce00-a4dc-11e8-8235-b34aa1f94763.png)
It's working for me, please could you write the exact steps to reproduce?

**Comment by ghost** [comment] 2018-08-20 23:18
With Python 3.6 installed on Windows 10:
Open cmd
Type node Index 
Select my Account
Alt + C: profile 9PJ8U8RY

What could also be the problem is the config. I wasn‘t completely sure what to change there, could you please explain that or link the site where it is explained?

**Comment by aperpen** [comment] 2018-08-21 22:56
Cannot reproduce, works fine for me. Although I cannot test on Windows, OS shouldn't be the problem here.
In config you just need to set up your account. For that just write your tag, and in pass field insert your token (https://github.com/aperpen/clash-royale-client#getting-a-token-android).

**Comment by aperpen** [comment] 2018-08-27 16:04
Closing as works fine for me. Feel free to reopen the issue if you consider it necessary.

**Closed as completed by aperpen** 2018-08-27 16:04 UTC
